#!/bin/bash

# launch python 2.7 in the custom python installation
# and sandbox calibre

export PYTHONHOME="/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/PYTHON/"
export CALIBRE_CONFIG_DIRECTORY='/home/phablet/.config/sturmreader.emanuelesorce/calibre/'
export CALIBRE_CACHE_DIRECTORY='/home/phablet/.cache/sturmreader.emanuelesorce/calibre/'
export CALIBRE_EXECUTABLES_PATH='/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/'
export CALIBRE_EXTENSIONS_PATH='/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/PYTHON/lib/calibre/calibre/plugins'
export CALIBRE_RESOURCES_PATH='/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/RESOURCES/'
export CALIBRE_PYTHON_PATH='/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/PYTHON/lib/calibre/'

unset LC_ALL
export LC_ALL="en_US.UTF-8"

python2.7 -B "$@"
