#!/bin/bash

# set up Calibre
if [ ! -d "/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/" ]; then
        echo "Calibre not set up - installing"
	echo "copying files..."
        mkdir -p '/home/phablet/.local/share/sturmreader.emanuelesorce/calibre'
        cp -r /opt/click.ubuntu.com/sturmreader.emanuelesorce/current/calibre/* '/home/phablet/.local/share/sturmreader.emanuelesorce/calibre/'
	echo "files copied!"
else
        echo "Calibre already installed"
fi
